### ISSUE TITLE
Cmake version required is too new

### ISSUE THREAD

**Issue by StephenLynx** [gamepopper/Vigilante-Game-Framework#2]
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.1.0 or higher is required.  You are running version 2.8.12.2

Can't even build it on CentOS.

**Comment by aggsol** [comment]
CMake  2.8.12 is nearly 5 years old, time to upgrade! The current stable version is 3.10! CMake is *VERY EASY* to compile and install yourself.

**Comment by StephenLynx** [comment]
You are looking it through the wrong perspective.
Is there any feature this project uses that is not on 2.8.12?

**Comment by StephenLynx** [comment]
VFrame/V3DObject.cpp:39:48: error: ‘fmodf’ was not declared in this scope
  Rotation.x = fmodf(Rotation.x + 360.0f, 360.0f);

Using gcc 6.

**Comment by StephenLynx** [comment]
VFrame/VBase.cpp:7:18: fatal error: term.h: No such file or directory
 #include <term.h>

**Comment by StephenLynx** [comment]
VFrame/VTimer.cpp:43:37: error: ‘find’ is not a member of ‘std’
  std::vector<VTimer*>::iterator i = std::find(timers.begin(), timers.end(), timer);

**Comment by StephenLynx** [comment]
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/ext/new_allocator.h:120:4: error: invalid initialization of non-const reference of type ‘glm::vec3& {aka glm::vec<3, float, (glm::qualifier)0u>&}’ from an rvalue of type ‘glm::vec<3, float, (glm::qualifier)0u>’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/sergio/Vigilante-Game-Framework/Example/../Example/States.h:19:0,
                 from /home/sergio/Vigilante-Game-Framework/Example/main.cpp:2:
/home/sergio/Vigilante-Game-Framework/Example/../Example/../VFrame/V3DModel.h:104:2: note:   initializing argument 1 of ‘V3DVertex::V3DVertex(glm::vec3&, glm::vec3&, glm::vec4&, glm::vec2&)’
  V3DVertex(glm::vec3& pos, glm::vec3& norm, glm::vec4& tint, glm::vec2& tex) : position(pos), normal(norm), color(tint), texCoord(tex) {}

**Comment by aggsol** [comment]
The Cmake file is in a poor state but should at least support CMake 3.8 that introduced `cxx_std_14`

**Comment by StephenLynx** [comment]
This project doesn't use that.

**Comment by gamepopper** [comment]
I've been making a number of updates to get the framework to build with SFML 2.5.0, however looking through some of the issues can be resolved by including some headers.

For V3DObject, add `#include #include <cmath>`, as that should have the definition of fmodf. For VTimer, add `#include <algorithm>` as that should have the find function. The V3DVertex one might just need the keyword `const` added to each of the parameters.

**Comment by gamepopper** [comment]
As for "term.h" include, you need to install libncurses

`sudo apt-get install libncurses5-dev`

So clearly it needs to be included as a dependency.
